# Copyright © 2023 KubeCub & Xinwei Xiong(cubxxw). All rights reserved.
# Licensed under the MIT License (the "License");
# you may not use this file except in compliance with the License.

builds:
- main: ./cmd/exporter
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goos:
    - linux
    - darwin
  goarch:
    - 386
    - amd64
    - arm
    - arm64
- main: ./cmd/syncer
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goos:
    - linux
    - darwin
  goarch:
    - 386
    - amd64
    - arm
    - arm64
before:
  hooks:
    - go mod download
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^Fix'
    - '^Refactor'
