# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...


builds:
  - binary: syncer
    id: syncer
    main: ./cmd/syncer/main.go
    goos:
      # - windows
      # - darwin
      - linux
    goarch:
      - amd64
      # - arm
      - arm64
    goarm:
      - 6
      - 7
  - binary: exporter
    id: exporter
    main: ./cmd/exporter/main.go
    goos:
      # - darwin
      - linux
    goarch:
      - amd64
      # - arm
      - arm64
    goarm:
      - 6
      - 7

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    files:
      - LICENSE.txt
      - README_{{.Os}}.md
      - README-{{.Os}}.md
      - CHANGELOG.md
      - CHANGELOG/*
      - docs/*
      - src: "*.md"
        dst: docs
      # a more complete example, check the globbing deep dive below
      - src: "*.md"
        dst: docs

        # Strip parent folders when adding files to the archive.
        strip_parent: true

        # File info.
        # Not all fields are supported by all formats available formats.
        #
        # Default: copied from the source file
        info:
          # Templates: allowed (since v1.14)
          owner: root

          # Templates: allowed (since v1.14)
          group: root

          # Must be in time.RFC3339Nano format.
          #
          # Templates: allowed (since v1.14)
          mtime: "{{ .CommitDate }}"

          # File mode.
          mode: 0644

    format_overrides:
    - goos: windows
      format: zip

nfpms:
  - id: packages
    builds:
      - syncer
    vendor: labring
    homepage: https://github.com/labring/sealos
    maintainer: fanux (https://github.com/fanux)
    description: Cloud OS distribution with Kubernetes as kernel
    license: Apach

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

# Default: './dist'
dist: _output/dist