version: "3"

services:
  syncer:
    build:
      context: .
      dockerfile: Dockerfile.syncer
    image: syncer
    container_name: syncer
    restart: always
    ports:
      - "8080:8080"
  exporter:
    build:
      context: .
      dockerfile: Dockerfile.exporter
    image: exporter
    container_name: exporter
    restart: always
    ports:
      - "9090:9090"
