# 设置基础镜像
FROM golang 

# 设置工作目录
WORKDIR /app

ENV GOPROXY=https://goproxy.cn

COPY . /app/

RUN go build -o /app/_output/bin/exporter /app/cmd/exporter/main.go

# 设置容器启动命令
CMD ["/app/_output/bin/exporter --help"]