FROM golang:1.20-alpine
# docker build -t syncer:1.0 -f ./Dockerfile.syncer .
WORKDIR /app

COPY . .

RUN apk update && apk add make

RUN make syncer

FROM alpine:latest

COPY --from=0 /app/_output/bin/platforms/linux/amd64/syncer /app/syncer

ENTRYPOINT ["/app/syncer"]
