# 设置基础镜像
FROM golang AS builder

# 设置工作目录
WORKDIR /app

ENV GOPROXY=https://goproxy.cn

RUN go get -d -v ./...
RUN go build -o syncer cmd/syncer/main.go

# 第二阶段
FROM scratch

# 从构建阶段复制二进制文件
COPY --from=builder /app/syncer /

# 设置容器启动命令
CMD ["/syncer"]
