# 设置基础镜像
FROM golang AS builder

# 设置工作目录
WORKDIR /app

ENV GOPROXY=https://goproxy.cn

# 将当前目录的所有文件复制到工作目录
COPY . .

# 构建 Go 程序
RUN go build -o exporter cmd/exporter/main.go
RUN go get -d -v ./...

# 第二阶段
FROM scratch

# 从构建阶段复制二进制文件
COPY --from=builder /app/exporter /

# 设置容器启动命令
CMD ["/exporter"]
