FROM golang:1.20-alpine
# docker build -t syncer:1.0 -f ./Dockerfile.syncer .
# 构建阶段1：构建二进制文件
FROM golang:1.20 as builder

# 设置工作目录
WORKDIR /app

# 复制项目文件到容器中
COPY cmd/exporter/main.go go.mod go.sum /app/

# 构建二进制文件
RUN CGO_ENABLED=0 GOOS=linux go build -o exporter main.go

# 构建阶段2：生成最终镜像
FROM alpine:latest

# 设置工作目录
WORKDIR /app

# 从构建阶段1中复制二进制文件到容器中
COPY --from=builder /app/syncer /app/syncer

# 运行二进制文件
CMD ["/app/syncer --help"]
