# 设置基础镜像
FROM golang AS builder

# 设置工作目录
WORKDIR /app

ENV GOPROXY=https://goproxy.cn

COPY . /app/

RUN go build -o /app/_output/bin/syncer /app/cmd/syncer/main.go

FROM scratch
COPY --from=builder /app/_output/bin/syncer /app
ENTRYPOINT ["/app/syncer --help"]