#!/usr/bin/env bash

# Copyright © 2023 KubeCub & Xinwei Xiong(cubxxw). All rights reserved.
#
# Licensed under the MIT License (the "License");
# you may not use this file except in compliance with the License.

#
# ==============================================================================
#
# Store this file as .git/hooks/commit-msg in your repository in order to
# enforce checking for proper commit message format before actual commits.
# You may need to make the script executable by 'chmod +x .git/hooks/commit-msg'.

# commit-msg use go-gitlint tool, install go-gitlint via `go get github.com/llorllale/go-gitlint/cmd/go-gitlint`
# go-gitlint --msg-file="$1"

# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.

YELLOW="\e[93m"
GREEN="\e[32m"
RED="\e[31m"
ENDCOLOR="\e[0m"

printMessage() {
   printf "${YELLOW}kubecub : $1${ENDCOLOR}\n"
}

printSuccess() {
   printf "${GREEN}kubecub : $1${ENDCOLOR}\n"
}

printError() {
   printf "${RED}kubecub : $1${ENDCOLOR}\n"
}

printMessage "Running the kubecub commit-msg hook."

# This example catches duplicate Signed-off-by lines.

test "" = "$(grep '^Signed-off-by: ' "$1" |
	 sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
	echo >&2 Duplicate Signed-off-by lines.
	exit 1
}

# TODO: go-gitlint dir set
GITLINT_DIR="./_output/tools/go-gitlint"

if ! command -v $GITLINT_DIR &>/dev/null; then
    echo "$GITLINT_DIR not found. Attempting to install it..."
    wget https://github.com/llorllale/go-gitlint/releases/download/v0.1.3/go-gitlint-0.1.3-linux-amd64.tar.gz
    tar -xvf go-gitlint-0.1.3-linux-amd64.tar.gz -C ./_output/tools/
    if [ $? -ne 0 ]; then
        printError "Failed to install $GITLINT_DIR. Please download the latest release from 'https://github.com/llorllale/go-gitlint/releases' and extract it to './_output/tools/' directory."
        exit 1
    fi
fi

$GITLINT_DIR \
    --msg-file=$1 \
    --subject-regex="^(build|chore|ci|docs|feat|feature|fix|perf|refactor|revert|style|test)(.*)?:\s?.*" \
    --subject-maxlen=150 \
    --subject-minlen=10 \
    --body-regex=".*" \
    --max-parents=1

if [ $? -ne 0 ]
then
    if ! command -v $GITLINT_DIR &>/dev/null; then
        printError "$GITLINT_DIR not found. Installing the go-gitlint tool..."
    make tools
    printError "Please make sure the installation was successful and re-run the commit-msg hook. If the problem persists, download the latest release from 'https://github.com/llorllale/go-gitlint/releases' and extract it to './_output/tools/' directory."
    fi
    printError "Please fix your commit message to match kubecub coding standards"
    printError "https://gist.github.com/cubxxw/126b72104ac0b0ca484c9db09c3e5694#file-githook-md"
    exit 1
fi