name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install go-gitlint
      run: make tools

    - name: Run githooks
      run: ./scripts/githooks/pre-commit && ./scripts/githooks/commit-msg

    - name: Test
      run: go test ./...

    - name: Build
      run: go build -v .
