name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Install go-gitlint

    - name: Install typos tool
      run: ./scripts/install_typos.sh

    - name: Install or Verify go-gitlint
      run: make tools || make tools.verify.go-gitlint

    - name: Check for typos
      run: typos --write-changes

    - name: Run commit-msg githook
      run: ./.git/hooks/commit-msg

    - name: Run tests
      run: go test ./... -v

    - name: Build
      run: go build -v .
