name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install make
      run: sudo apt-get install make

    - name: Install go-gitlint
      run: make tools
      if: "contains(github.event.head_commit.message, '^(build|chore|ci|docs|feat|feature|fix|perf|refactor|revert|style|test)(.*)?:\s?.*')"

    - name: Run commit-msg hook
      run: ./.git/hooks/commit-msg
