name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install go-gitlint
      run: |
        make tools
        make tools.verify.go-gitlint

    - name: Run githooks
      run: |
        chmod +x scripts/githooks/*
        scripts/githooks/commit-msg
        scripts/githooks/pre-commit

    - name: Test
      run: go test ./...
