name: Main Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install go-gitlint
      run: make tools
      needs: [checkout, setup-go]

    - name: Run commit hooks
      run: ./scripts/githooks/commit-msg && ./scripts/githooks/pre-commit
      needs: [install-go-gitlint]
