name: Main Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install make
      run: sudo apt-get install make

    - name: Install go-gitlint
      run: make tools

    - name: Run commit-msg hook
      run: git commit -m "test: this commit is allowed file sizes up to 50MB"
