name: Test repository spelling check
on:
    push:
        branches:
          - main
    pull_request:
        branches:
          - main
    workflow_dispatch:

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v2

    - name: Check spelling of md
      uses: crate-ci/typos@master
      with: 
        files: ./CONTIRIBUTING.md

    - name: Use custom config file
      uses: crate-ci/typos@master
      with: 
        files: ./README.md