# Copyright © 2023 KubeCub open source community. All rights reserved.
# Licensed under the MIT License (the "License");
# you may not use this file except in compliance with the License.

name: Kubecub Sync labels

on:
  push:
    branches:
      - main
    # paths:
    #   - .github/sync_labels.yml

# uses: kubecub/github-label-syncer@v1.2.0
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@1.0.0
        - name: Github lables pull and synchronize
          uses: micnncim/action-label-syncer@v1
          with:
            manifest: .github/sync_labeler.yml
            token: ${{ secrets.BOT_GITHUB_TOKEN }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
