name: Check for typos

on: [push, pull_request]

jobs:
  check_typos:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Check for typos
      uses: codespell-project/actions-codespell@master
      with:
        skip: .git,*.png,*.jpg
        ignore_words_file: .github/workflows/codespell_ignore_words.txt
        paths: './CONTRIBUTING.md ./README.md'
      working-directory: ./

